# Generated by Django 4.1.4 on 2023-01-21 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
    ]
