# Generated by Django 4.1.7 on 2023-02-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_table_column_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
