# Generated by Django 4.1.7 on 2023-03-12 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='column',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
