# Generated by Django 4.1.7 on 2023-03-12 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_column_members_alter_column_name_alter_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='members',
        ),
        migrations.AddField(
            model_name='table',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
