# Generated by Django 4.1.7 on 2023-04-19 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachments',
        ),
    ]
