# Generated by Django 4.1.7 on 2023-05-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_task_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
