# Generated by Django 4.1.7 on 2023-05-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
