# Generated by Django 4.1.7 on 2023-05-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_checkbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complition', models.BooleanField(default=False)),
                ('date', models.DateField()),
            ],
        ),
    ]
