# Generated by Django 4.1.7 on 2023-05-15 15:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.task'),
        ),
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 20, 29, 17, 161934)),
        ),
    ]
