# Generated by Django 4.1.7 on 2023-05-15 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_dates_date_alter_dates_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 0, 53, 33, 281601)),
        ),
    ]
